services:
  - type: static
    name: moduler-ai-app
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: API_KEY
        sync: false # Render panelinden manuel girmeniz gerekecek
    routes:
      - type: rewrite
        source: /*
        destination: /index.html